name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install neovim
        uses: rhysd/action-setup-vim
        with:
          neovim: true
          version: nightly

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks

      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: npm

      - name: Setup tools
        shell: bash
        run: |
          luarocks install vusted

      - name: Run tests
        shell: bash
        run: npm run test

